#+title: mouthpiecer-tui

* About

*mouthpiecer-tui* is a Python based terminal user interface to a [[https://www.knack.com][Knack]] database.

The Mouthpiecer Knack front end can be found here: [[https://aleksozolins.knack.com/mouthpiecer#home/]]

- The app is meant for individual users to manage their French Horn mouthpiece collection (really).
- Users can also view the collections of other "mouthpiecers" and can arrange mouthpiece trades as well.
- For now, some features have been removed from the front end and will be re-introduced as the cli develops.

Ultimately, the tui should exactly mirror the feature-set of the web front end.

* Compatibility

- [X] macOS
- [X] Linux
- [X] Windows

* Installation Instructions (venv)

From the terminal:

1. ~git clone https://github.com/aleksozolins/mouthpiecer-tui.git~
2. ~cd mouthpiecer-tui~
3. ~python3 -m venv .venv~
4. ~source .venv/bin/activate~
5. ~pip3 install -r requirements.txt~

To run the program:

~python3 mouthpiecer.py~

To exit the virtual environment after quitting:

~deactivate~

* Dependencies

- [[https://docs.python-requests.org/][requests]]
- [[https://rich.readthedocs.io/][rich]]

* Configuration (Optional)

The app uses default Knack API credentials. To override them, set environment variables:

#+begin_src shell
export KNACK_APP_ID="your-app-id"
export KNACK_API_KEY="your-api-key"
#+end_src


